### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#15]
# CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

## Root Cause Analysis

The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template doesn't meet the AWS ECR repository naming pattern requirements. AWS ECR repository names must follow specific pattern constraints, and using a generic placeholder like "repositoryName" violates these constraints.

**Confidence Level**: 95%

### Error Message
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Problematic Code
**File**: `cloudformation-templates/infrastructure.yml`
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements.
2. Use a dynamic repository name that matches the environment name or use the same repository name defined in the workflow file.
3. Replace the static "repositoryName" with a reference to the environment name parameter.
4. Ensure the repository name follows the ECR naming pattern (must contain only lowercase letters, numbers, hyphens, underscores, and periods).

### Recommended Fix

Option 1: Use a dynamic name based on environment parameter:
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

Option 2: Match the name used in the workflow file:
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

## Additional Information

AWS ECR repository names must follow specific naming patterns:
- Must contain only lowercase letters, numbers, hyphens, underscores, and periods
- Cannot start or end with a hyphen
- Cannot contain consecutive hyphens
- Must be between 2 and 256 characters in length
