### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#16]
## Root Cause Analysis

The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template doesn't follow AWS ECR naming pattern requirements. AWS ECR repository names must follow specific naming conventions, and the current value is being treated as a literal placeholder rather than a valid repository name.

### Finding: Invalid ECR Repository Name Pattern

**Impacted File:** `cloudformation-templates/infrastructure.yml`

**Problematic Code:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

**Error Message:**
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Replace the static "repositoryName" with a valid ECR repository name that follows AWS naming conventions
2. Consider using a dynamic name based on the environment name to ensure uniqueness
3. Make sure the repository name contains only lowercase letters, numbers, hyphens, underscores, and periods
4. Update the CloudFormation template with the corrected repository name

### Recommended Fix:

```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-ecr-repo
```

This uses the environment name (which is already being passed as a parameter) with a suffix to create a valid, dynamic repository name that will follow AWS ECR naming conventions.
