### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#17]
# Root Cause Analysis: CloudFormation Deployment Failure

## Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR repository naming requirements. ECR repository names must follow specific pattern constraints.

### Error Message
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements.
2. ECR repository names must match the pattern: `^[a-z0-9][a-z0-9-_]{0,254}$`
3. Replace the generic "repositoryName" with a valid name that follows the pattern.
4. Consider using a dynamic name based on the environment name to ensure uniqueness.

### Corrected Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-app-repo
```

This uses the environment name as a prefix for the repository name, ensuring it follows the required pattern and is unique per environment.
