### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#18]
# Root Cause Analysis

## Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR repository naming pattern requirements.

## Confidence Level
95%

### Error Details
The CloudFormation stack creation fails with the following error:
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Root Cause
The ECR repository name "repositoryName" does not comply with AWS ECR naming pattern requirements. ECR repository names must follow specific pattern constraints, including:
- Lowercase letters
- Numbers
- Hyphens
- Underscores

## Solution Plan

1. Update the ECR repository name to follow AWS ECR naming requirements
2. Use a dynamic name based on the environment name to ensure uniqueness
3. Ensure the name follows the pattern: lowercase letters, numbers, hyphens, underscores
4. Update the CloudFormation template with the corrected repository name

### Recommended Fix
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repository
```

This uses the environment name (which is derived from the GitHub repository name) as a prefix for the ECR repository name, ensuring it follows the required pattern and is unique for each deployment.
