### ISSUE TITLE
Fix ECR Repository Name Format and Consistency Issues

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#19]
# Root Cause Analysis: CloudFormation Deployment Failure

## Summary
The CloudFormation stack deployment is failing due to invalid ECR repository name format and inconsistency between configuration files.

### Finding 1: Invalid ECR Repository Name Format
**Confidence Level:** 95%

#### Analysis
The CloudFormation stack update failed because the ECR repository name "repositoryName" violates AWS ECR repository naming requirements. ECR repository names must follow a specific pattern - they must start with a letter and can only contain lowercase letters, numbers, hyphens, underscores, and periods. The use of uppercase letters in "repositoryName" is causing the validation constraint failure.

#### Impacted File
`cloudformation-templates/infrastructure.yml`

#### Code Snippet
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

#### Error Log
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Finding 2: Repository Name Inconsistency
**Confidence Level:** 95%

#### Analysis
There is an inconsistency between the repository name in the CloudFormation template ("repositoryName") and the GitHub workflow file ("reponame"), which would cause issues when the web application deployment job tries to push to the ECR repository.

#### Impacted File
`.github/workflows/deploy.yml`

#### Code Snippet
```yaml
- name: Build, tag, and push webapp image
  id: build-image
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    ECR_REPOSITORY: reponame
    IMAGE_TAG: webapp-${{ github.sha }}
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to use only lowercase letters, numbers, hyphens, underscores, and periods.
2. Ensure the repository name is consistent between the CloudFormation template and the GitHub workflow.
3. Change the RepositoryName property in cloudformation-templates/infrastructure.yml to:
   ```yaml
   ImageRepository:
     Type: AWS::ECR::Repository
     Properties:
       RepositoryName: repository-name
   ```
4. Update the ECR_REPOSITORY environment variable in the GitHub workflow to match:
   ```yaml
   ECR_REPOSITORY: repository-name
   ```
5. Consider using a variable or output from the infrastructure deployment to ensure consistency.
6. Alternatively, consider using the AWS account ID and repository name to create a fully qualified repository name that's guaranteed to be unique.

## References
- [AWS ECR Repository Naming Requirements](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-create.html)
- [CloudFormation ECR Repository Resource Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html)
