### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#20]
# CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

## Root Cause Analysis
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR naming pattern requirements. AWS ECR repository names must follow specific pattern constraints, typically allowing only lowercase letters, numbers, hyphens, underscores, and periods with certain length limitations.

**Confidence Level:** 95%

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

### Error Message
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Update the ECR repository name to follow AWS ECR naming requirements:
   - ECR repository names must contain only lowercase letters, numbers, hyphens, underscores, and periods
   - Names must start with a letter and can be 2-256 characters long
   - Names cannot end with a hyphen or contain consecutive hyphens

2. Replace the hardcoded "repositoryName" with a dynamic name based on the environment:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

3. Alternatively, you can remove the RepositoryName property completely to let AWS generate a valid name automatically:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
```

4. Deploy the updated CloudFormation template to resolve the validation error.
