### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#21]
# CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

## Root Cause Analysis

The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template doesn't meet AWS ECR naming pattern requirements. ECR repository names must follow the pattern: `^[a-zA-Z0-9-_/]+$`, and cannot contain uppercase letters.

**Confidence Level:** 95%

### Error Details

The following error was observed in the CloudFormation stack events:

```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Impacted File

**File Path:** `cloudformation-templates/infrastructure.yml`

**Problematic Code:**
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan

1. Update the ECR repository name to follow AWS naming requirements
2. Use a valid name that follows the pattern `^[a-z0-9-_/]+$` (lowercase letters, numbers, hyphens, underscores, and forward slashes)
3. Consider using a dynamic name based on the environment name to ensure uniqueness
4. Replace the static value with a valid name or reference a parameter

### Recommended Fix:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub "${EnvironmentName}-repo"
```

This change will:
- Use a valid name format that complies with AWS ECR naming requirements
- Create a unique repository name based on the environment name
- Ensure consistency with the rest of the CloudFormation template's naming conventions
