### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#22]
# CloudFormation Deployment Failure: Invalid ECR Repository Name

## Root Cause Analysis
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template violates the AWS ECR repository naming pattern requirements. ECR repository names must follow specific naming conventions, typically lowercase alphanumeric characters, hyphens, underscores, and forward slashes.

### Error Details
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming conventions
2. Replace the hardcoded "repositoryName" with a valid name that follows the pattern (lowercase letters, numbers, hyphens, underscores)
3. Consider using a dynamic name based on the environment name parameter for better consistency
4. Update the infrastructure.yml file with the corrected code:

```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

5. Commit the changes and push to the repository
6. Re-run the workflow to verify the fix
