### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#23]
# CloudFormation Deployment Failure: Invalid ECR Repository Name

## Root Cause Analysis

The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not comply with AWS ECR repository naming pattern requirements. 

**Confidence Level**: 95%

### Finding: Invalid ECR Repository Name Pattern

**Impacted File**: `cloudformation-templates/infrastructure.yml`

**Problematic Code**:
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

**Error Message**:
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements:
   - Repository names must start with a letter
   - Repository names can only contain lowercase letters, numbers, hyphens, underscores, and periods
   - Repository names cannot contain uppercase letters or spaces
   - Repository names must be between 2 and 256 characters

2. Modify the infrastructure.yml file by changing the RepositoryName property to use a valid name:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: hwum-cfndeployment-repo
```

3. Alternatively, use a dynamic name based on the environment name parameter:

```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

4. Commit the changes and re-run the workflow to deploy the infrastructure.
