### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Signal Timeout

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#24]
# CloudFormation Deployment Failure: EC2 Instance Signal Timeout

## Root Cause Analysis

The CloudFormation deployment is failing because the EC2 instance is configured with an extremely short ResourceSignal timeout (10 seconds) in its CreationPolicy. The EC2 instance cannot initialize, configure itself, and send the required success signal back to CloudFormation within this short timeframe, causing the deployment to fail.

**Confidence Level**: 95%

### Finding: EC2 Instance Signal Timeout Too Short

**Impacted File**: `cloudformation-templates/infrastructure.yml`

**Problematic Code**:
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

**Error Message**:
```
2025-06-13T22:14:38.764000+00:00|  EC2Instance |  AWS::EC2::Instance |  Failed to receive 1 resource signal(s) within the specified duration
```

## Solution Plan

1. Increase the ResourceSignal timeout in the CreationPolicy to a more reasonable duration. EC2 instances typically need several minutes to initialize.

2. Update the infrastructure.yml file by modifying the CreationPolicy section:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M  # Changed from PT10S to PT5M (5 minutes)
```

3. Additionally, if you want the EC2 instance to properly send a signal back to CloudFormation, you need to include user data that installs and runs the cfn-signal command. Add the following to the EC2Instance properties:

```yaml
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash -xe
        yum update -y
        yum install -y aws-cfn-bootstrap
        # Signal the status from this instance to CloudFormation
        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
```

4. Alternatively, if you don't need the EC2 instance to signal completion, you can simply remove the CreationPolicy section entirely.
