### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#25]
## Root Cause Analysis

The CloudFormation deployment is failing because the ECR repository name in the infrastructure template doesn't meet AWS ECR naming pattern requirements. The error occurs during the "Deploy infrastructure with CloudFormation" step.

**Confidence Level:** 95%

### Invalid ECR Repository Name Pattern

**Impacted File:** `cloudformation-templates/infrastructure.yml`

**Problem Code:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

**Error Message:**
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

The hardcoded value `repositoryName` does not meet AWS ECR naming pattern requirements. ECR repository names must follow specific pattern constraints, typically allowing lowercase letters, numbers, hyphens, and underscores in specific formats.

## Solution Plan

1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements
2. Replace the hardcoded "repositoryName" with a dynamic name based on the environment name
3. Ensure the repository name follows the pattern requirements (lowercase letters, numbers, hyphens, underscores)
4. Consider using the environment name as part of the repository name for uniqueness

**Recommended Fix:**
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

This will create a repository name that includes the environment name (which is derived from the GitHub repository name) followed by "-repo", ensuring it meets the ECR naming pattern requirements.

## Additional Information

AWS ECR repository names must follow these requirements:
- Must start with a letter
- Can contain lowercase letters, numbers, hyphens, underscores, and periods
- Cannot contain uppercase letters or other special characters

The current workflow derives the environment name from the GitHub repository name, which ensures it will be properly formatted and can be used as part of the ECR repository name.
