### ISSUE TITLE
Fix ECR Repository Name Pattern Validation Error in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#26]
# Root Cause Analysis: CloudFormation Deployment Failure

## Problem Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure template does not meet AWS ECR repository naming requirements.

## Error Details
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

## Root Cause
AWS ECR repository names must follow a specific pattern, which includes allowing only lowercase letters, numbers, hyphens, underscores, and periods. The hardcoded value "repositoryName" in the CloudFormation template is invalid because it uses mixed case (camelCase).

## Impacted File
`cloudformation-templates/infrastructure.yml`

## Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan
1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements.
2. Change the repository name to lowercase or use a dynamic name based on the environment.
3. Modify the CloudFormation template at cloudformation-templates/infrastructure.yml:

```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repository
```

4. This change will use the environment name (which is already properly formatted with hyphens) as part of the repository name.
5. Alternatively, you could use a hardcoded lowercase name like:

```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryname
```

6. Make sure to update the ECR_REPOSITORY environment variable in the deploy-web-app job to match the new repository name.

## Confidence Level
95% - The error message clearly indicates a pattern validation failure on the RepositoryName property, and AWS ECR has well-documented naming requirements.
