### ISSUE TITLE
Fix EC2 Instance Resource Signal Timeout in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#27]
# Root Cause Analysis: EC2 Instance Resource Signal Timeout

## Problem Summary
The CloudFormation deployment is failing because the EC2 instance is not sending the required resource signal within the specified timeout period of 10 seconds (PT10S).

## Error Details
```
Failed to receive 1 resource signal(s) within the specified duration
```

## Root Cause
The EC2Instance resource has a CreationPolicy that requires a signal from the instance to indicate successful creation, but the timeout is too short for the instance to boot up, configure itself, and send the signal. Additionally, there is no UserData script configured to send the required signal back to CloudFormation.

## Impacted File
`cloudformation-templates/infrastructure.yml`

## Problematic Code
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

## Solution Plan
1. Increase the ResourceSignal timeout in the EC2Instance's CreationPolicy to allow more time for the instance to boot up and send the signal.
2. Add a UserData script to send the required signal back to CloudFormation.
3. Modify the CloudFormation template at cloudformation-templates/infrastructure.yml:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash -xe
        yum update -y
        yum install -y aws-cfn-bootstrap
        # Signal the status from this instance to CloudFormation
        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M  # Increase from PT10S (10 seconds) to PT5M (5 minutes)
```

4. If the EC2 instance is only for testing purposes and doesn't need to send signals, you can remove the CreationPolicy entirely.

## Confidence Level
95% - The error message clearly indicates a timeout waiting for a resource signal, and the CloudFormation template shows a very short timeout period without the necessary UserData script to send the signal.
