### ISSUE TITLE
Fix ECR Repository Resource Conflict in CloudFormation Template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#28]
# Root Cause Analysis: ECR Repository Resource Conflict

## Problem Summary
The CloudFormation deployment is failing because there are two ECR repository resources defined in the infrastructure.yml template that are trying to use the same repository name.

## Error Details
```
reponame already exists in stack arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/aeced980-4884-11f0-80fb-0633484e73dd
```

## Root Cause
AWS CloudFormation does not allow duplicate resource names within the same stack. In the infrastructure.yml template, there are two ECR repository resources (ImageRepository and ImageRepository2) that are both configured to use the same repository name "reponame". When CloudFormation attempts to create the second repository with the same name, it fails because that name is already in use by the first repository.

## Impacted File
`cloudformation-templates/infrastructure.yml`

## Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

## Solution Plan
1. Modify the CloudFormation template to ensure each ECR repository has a unique name.
2. Open the file cloudformation-templates/infrastructure.yml
3. Change the repository name for ImageRepository2 to be different from the first one:

```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame2  # Changed from 'reponame' to 'reponame2'
```

4. Alternatively, if you don't need two separate repositories, you can simply remove the duplicate ImageRepository2 resource.
5. If you need to create multiple repositories with dynamic names, consider using the environment name as part of the repository name:

```yaml
ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-reponame2
```

6. Make sure to update any references to these repositories in other parts of the code if necessary.

## Confidence Level
98% - The error message clearly indicates a resource conflict with the same repository name, and the CloudFormation template shows two resources with identical repository names.
