### ISSUE TITLE
Fix CloudFormation Stack in ROLLBACK_COMPLETE State

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#29]
# Root Cause Analysis: CloudFormation Stack in ROLLBACK_COMPLETE State

## Problem Summary
The CloudFormation deployment is failing because the stack is in a ROLLBACK_COMPLETE state, which is a terminal state that prevents further updates.

## Error Details
```
Stack:arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/36747960-4828-11f0-bbce-0a680864902d is in ROLLBACK_COMPLETE state and can not be updated.
```

## Root Cause
When a CloudFormation stack creation fails, AWS automatically rolls back all resources and puts the stack in a ROLLBACK_COMPLETE state. This is a terminal state, and CloudFormation does not allow updates to stacks in this state. The only operations allowed on a stack in ROLLBACK_COMPLETE state are deletion or viewing stack information.

## Impacted File
`.github/workflows/deploy.yml`

## Problematic Code
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

## Solution Plan
1. Add a step to delete the stack if it's in ROLLBACK_COMPLETE state before attempting to deploy:

```yaml
- name: Check and delete stack if in ROLLBACK_COMPLETE state
  id: check-stack
  run: |
    STACK_NAME="${{ steps.env-name.outputs.environment }}-infra"
    STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "STACK_NOT_FOUND")
    echo "Stack status: $STACK_STATUS"
    
    if [[ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]]; then
      echo "Stack is in ROLLBACK_COMPLETE state, deleting stack before redeployment"
      aws cloudformation delete-stack --stack-name "$STACK_NAME"
      
      # Wait for stack deletion to complete
      echo "Waiting for stack deletion to complete..."
      aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
      echo "Stack deletion completed"
    fi

- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

2. Alternatively, you could manually delete the stack through the AWS Console or CLI before running the workflow again.

3. To prevent future failures that might lead to ROLLBACK_COMPLETE state, add more robust error handling and validation to your CloudFormation template.

## Confidence Level
95% - The error message clearly indicates that the stack is in ROLLBACK_COMPLETE state, which is a well-documented limitation of AWS CloudFormation.
