### ISSUE TITLE
CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#30]
# CloudFormation Deployment Failure: Invalid ECR Repository Name Pattern

## Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template does not meet the AWS ECR repository naming pattern requirements.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Impacted File**: `cloudformation-templates/infrastructure.yml`
- **Error Message**: `Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

## Solution Plan
1. Update the ECR repository name in the CloudFormation template to follow AWS ECR naming requirements.
2. ECR repository names must match the pattern: `^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$`
3. Replace the static "repositoryName" with a dynamic name based on the environment name or use all lowercase.

### Option 1: Use dynamic naming with environment variable
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-repo
```

### Option 2: Use all lowercase for the repository name
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryname
```

## Additional Information
- AWS ECR repository names have specific pattern constraints that require lowercase alphanumeric characters, hyphens, and must start with a letter.
- The current implementation uses a mixed-case name "repositoryName" which violates these constraints.
- The workflow status was "UPDATE_ROLLBACK_COMPLETE" indicating that CloudFormation attempted to roll back after the failure.
