### ISSUE TITLE
CloudFormation Deployment Failure: EC2 Instance Signal Timeout

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#31]
# CloudFormation Deployment Failure: EC2 Instance Signal Timeout

## Summary
The CloudFormation deployment is failing because the EC2 instance is configured with a CreationPolicy that requires a signal within 10 seconds (PT10S), but the instance is unable to send this signal within the specified timeout period.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Impacted File**: `cloudformation-templates/infrastructure.yml`
- **Error Message**: `Failed to receive 1 resource signal(s) within the specified duration`

### Problematic Code
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

## Solution Plan
1. Increase the timeout value in the CreationPolicy to allow sufficient time for the EC2 instance to boot and send the signal.
2. A reasonable timeout would be at least 5 minutes (PT5M) or more.
3. Add a UserData script to install and run the cfn-signal command to send the required signal back to CloudFormation.

### Implementation
```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash -xe
        yum update -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT5M
```

## Additional Information
- 10 seconds is too short for an EC2 instance to boot up, install the CloudFormation helper scripts, and send the required signal.
- The EC2 instance needs a UserData script to send the signal back to CloudFormation.
- The typical boot time for an EC2 instance can be 1-3 minutes, so a timeout of at least 5 minutes is recommended.
- The workflow status was "ROLLBACK_COMPLETE" indicating that CloudFormation attempted to roll back after the failure.
