### ISSUE TITLE
CloudFormation Deployment Failure: ECR Repository Name Conflict

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#32]
# CloudFormation Deployment Failure: ECR Repository Name Conflict

## Summary
The CloudFormation deployment is failing because the template defines two ECR repositories (ImageRepository and ImageRepository2) with the same repository name "reponame". AWS ECR repository names must be unique within an account.

## Root Cause Analysis
- **Confidence Level**: 100%
- **Impacted File**: `cloudformation-templates/infrastructure.yml`
- **Error Message**: `reponame already exists in stack arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/aeced980-4884-11f0-80fb-0633484e73dd`

### Problematic Code
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

## Solution Plan
1. Modify the CloudFormation template to use unique repository names for each ECR repository.
2. Update the ImageRepository2 resource to use a different repository name.

### Implementation
```yaml
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame2
```

## Additional Information
- AWS ECR repository names must be unique within an account.
- The error occurs because CloudFormation is attempting to create a second repository with the same name.
- Alternatively, if you don't need two separate repositories, you could remove the ImageRepository2 resource entirely.
- The commit message "New: Add one more imageRepo" indicates that a second repository was intentionally added, but the name conflict was overlooked.
