### ISSUE TITLE
CloudFormation Deployment Failure: Stack in ROLLBACK_COMPLETE State

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#33]
# CloudFormation Deployment Failure: Stack in ROLLBACK_COMPLETE State

## Summary
The CloudFormation deployment is failing because the stack is in a ROLLBACK_COMPLETE state, which is a terminal state that prevents further updates. This state occurs when a stack creation fails and CloudFormation automatically rolls back all resources.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Impacted File**: `.github/workflows/deploy.yml`
- **Error Message**: `Stack:arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/36747960-4828-11f0-bbce-0a680864902d is in ROLLBACK_COMPLETE state and can not be updated.`

### Problematic Code
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

## Solution Plan
1. Add a step to check if the stack is in ROLLBACK_COMPLETE state before attempting to deploy.
2. If the stack is in ROLLBACK_COMPLETE state, delete it first and then proceed with the deployment.

### Implementation
```yaml
- name: Check if stack exists and is in ROLLBACK_COMPLETE state
  id: check-stack
  run: |
    STACK_NAME="${{ steps.env-name.outputs.environment }}-infra"
    STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "STACK_NOT_FOUND")
    echo "stack-status=$STACK_STATUS" >> "$GITHUB_OUTPUT"
    if [[ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]]; then
      echo "Stack is in ROLLBACK_COMPLETE state, deleting it first..."
      aws cloudformation delete-stack --stack-name "$STACK_NAME"
      aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
      echo "Stack deleted successfully"
    fi

- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

## Additional Information
- Once a CloudFormation stack is in ROLLBACK_COMPLETE state, it cannot be updated - it must be deleted and recreated.
- The ROLLBACK_COMPLETE state indicates that a previous stack creation attempt failed and CloudFormation automatically rolled back all resources.
- The workflow should be modified to handle this state by deleting the stack before attempting to deploy again.
- This is a common issue when working with CloudFormation stacks, especially during development and testing phases.
