### ISSUE TITLE
Fix invalid ECR repository name pattern in CloudFormation template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#34]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The CloudFormation deployment is failing because the ECR repository name "repositoryName" in the infrastructure.yml template does not meet AWS ECR repository naming pattern requirements. ECR repository names must follow specific pattern constraints: they must contain only letters, numbers, hyphens, underscores, and periods, and cannot start with a period or hyphen.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: repositoryName
```

### Error Message
```
Resource handler returned message: "Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])" (RequestToken: fe243b21-e8d1-3166-b53d-653bc36bb3f8, HandlerErrorCode: InvalidRequest)
```

## Solution Plan

1. Update the ECR repository name in the infrastructure.yml file to follow AWS ECR naming requirements
2. Use a name that follows the pattern: letters, numbers, hyphens, underscores, and periods (cannot start with period or hyphen)
3. Consider using a dynamic name based on the environment name to ensure uniqueness
4. Replace the static "repositoryName" with a more descriptive and valid name

### Recommended Fix
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: !Sub ${EnvironmentName}-ecr-repo
```

This uses the environment name (which is already properly formatted) with a suffix to create a valid repository name.
