### ISSUE TITLE
Fix EC2 instance ResourceSignal timeout in CloudFormation template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#35]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The CloudFormation deployment is failing because the EC2 instance is configured with an extremely short timeout (PT10S = 10 seconds) in its CreationPolicy ResourceSignal. The instance doesn't have enough time to boot up, install the CloudFormation helper scripts, and send the success signal back to CloudFormation within this 10-second window.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# EC2 Instance with short timeout
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT10S
```

### Error Message
```
Failed to receive 1 resource signal(s) within the specified duration
```

## Solution Plan

1. Increase the ResourceSignal timeout value in the CreationPolicy to give the EC2 instance enough time to boot up and signal completion
2. A typical EC2 instance needs at least several minutes to boot up and configure itself
3. Update the timeout value from PT10S (10 seconds) to PT15M (15 minutes) which is a more reasonable timeout for EC2 instances

### Recommended Fix
```yaml
# EC2 Instance with reasonable timeout
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SubnetId: !Ref PublicSubnetOne
    SecurityGroupIds:
      - !Ref ContainerSecurityGroup
    ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (adjust for your region)
    Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName}-test-instance"
  CreationPolicy:
    ResourceSignal:
      Timeout: PT15M
```

Additionally, ensure the EC2 instance has the necessary CloudFormation helper scripts installed and is configured to send the signal. If the instance is not set up to send a signal at all, you should either:
1. Add UserData to install and run cfn-signal, or
2. Remove the CreationPolicy if you don't need to wait for the instance to be fully configured
