### ISSUE TITLE
Fix duplicate ECR repository names in CloudFormation template

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#36]
## Root Cause Analysis

**Confidence Level:** 100%

### Issue Summary
The CloudFormation deployment is failing because there are two ECR repository resources (ImageRepository and ImageRepository2) that are both trying to create repositories with the same name "reponame". AWS CloudFormation doesn't allow duplicate resource names within the same stack, resulting in a resource conflict error during deployment.

### Impacted File
`cloudformation-templates/infrastructure.yml`

### Problematic Code
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame
```

### Error Message
```
reponame already exists in stack arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/aeced980-4884-11f0-80fb-0633484e73dd
```

## Solution Plan

1. Ensure each ECR repository has a unique name by modifying the RepositoryName property for one or both resources
2. Either remove one of the duplicate repository definitions or give them different names
3. Consider using dynamic naming with the environment name as a prefix to ensure uniqueness

### Recommended Fix
Option 1: Use unique repository names if you need both repositories:
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

ImageRepository2:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame2
```

Option 2: Remove the duplicate if only one repository is needed:
```yaml
# ECR Repository
ImageRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: reponame

# Remove or comment out the duplicate ImageRepository2 resource
```
