### ISSUE TITLE
Fix CloudFormation deployment failure due to ROLLBACK_COMPLETE stack state

### ISSUE THREAD

**Issue by parantr** [hwum/CFNDeployment#37]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The CloudFormation deployment is failing because the stack "hwum-CFNDeployment-infra" is in a ROLLBACK_COMPLETE state, which is a terminal state in AWS CloudFormation. When a stack is in ROLLBACK_COMPLETE state, it means that the stack creation failed and AWS automatically rolled back all the changes. CloudFormation does not allow updating a stack that is in this state - it must be deleted first and then recreated.

### Impacted File
`.github/workflows/deploy.yml`

### Problematic Code
```yaml
- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

### Error Message
```
Stack:arn:aws:cloudformation:us-east-2:***:stack/hwum-CFNDeployment-infra/36747960-4828-11f0-bbce-0a680864902d is in ROLLBACK_COMPLETE state and can not be updated.
```

## Solution Plan

1. Delete the failed CloudFormation stack before attempting to deploy again
2. Add a step to the workflow that checks if the stack exists and is in ROLLBACK_COMPLETE state
3. If the stack is in ROLLBACK_COMPLETE state, delete it before attempting to create/update it
4. Modify the workflow to handle this scenario automatically

### Recommended Fix

Add a new step before the CloudFormation deployment step to check and handle stacks in ROLLBACK_COMPLETE state:

```yaml
- name: Check if stack exists and is in ROLLBACK_COMPLETE state
  id: check-stack
  run: |
    STACK_NAME="${{ steps.env-name.outputs.environment }}-infra"
    echo "Checking if stack $STACK_NAME exists and its status..."
    
    # Check if stack exists and get its status
    if STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null); then
      echo "Stack exists with status: $STACK_STATUS"
      echo "stack_exists=true" >> "$GITHUB_OUTPUT"
      echo "stack_status=$STACK_STATUS" >> "$GITHUB_OUTPUT"
      
      # If stack is in ROLLBACK_COMPLETE state, it needs to be deleted
      if [[ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]]; then
        echo "Stack is in ROLLBACK_COMPLETE state, deleting it..."
        aws cloudformation delete-stack --stack-name "$STACK_NAME"
        echo "Waiting for stack deletion to complete..."
        aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
        echo "Stack deleted successfully."
        echo "stack_deleted=true" >> "$GITHUB_OUTPUT"
      else
        echo "stack_deleted=false" >> "$GITHUB_OUTPUT"
      fi
    else
      echo "Stack does not exist."
      echo "stack_exists=false" >> "$GITHUB_OUTPUT"
      echo "stack_deleted=false" >> "$GITHUB_OUTPUT"
    fi

- name: Deploy infrastructure with CloudFormation
  id: infrastructure-stack
  uses: aws-actions/aws-cloudformation-github-deploy@v1
  with:
    name: ${{ steps.env-name.outputs.environment }}-infra
    template: cloudformation-templates/infrastructure.yml
    role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-cloudformation-stack-role
    no-fail-on-empty-changeset: "1"
    parameter-overrides: >-
      EnvironmentName=${{ steps.env-name.outputs.environment }},
      VPC=${{ steps.vpc.outputs.vpc-id }},
      PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
      PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
```

This solution adds a step that checks if the stack exists and is in ROLLBACK_COMPLETE state. If it is, the step deletes the stack before the deployment step attempts to create/update it.
